// $Id$

/*
    CompSL scripting language
    Copyright (C) 2007  Thomas Jones & John Peberdy

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

#ifndef COMPSL_VM_H_
#define COMPSL_VM_H_

#include "compsl.h"
#include "syms.h"

///< Size of the arithmatic stack
#define VM_STACK_SIZE 256

///< Maximum number of global variables (note currently cannot be  increased
///< since internal addresses are only 1 byte)
#define VM_MAX_GVARS 256

///< initial size of function table, may be resized?
#define VM_NATIVEFN_INIT_SIZE 64

struct _VM_t
{
	varTable vt;       ///< variable table, holds global variables
    nativeFN *natives; ///< native function table
    uint16_t ncnt;     ///< number of native functions

    COMPSL_ERROR errorno; ///<holds the error code of the last error generated by this VM
};

#endif
